name: ZAP-Test

on:
  push: 
    branches: [ main ]

jobs: 
  build: 
    runs-on: ubuntu-18.04
    steps: 
      - uses: actions/checkout@v2
      - name: Build Image
        run: |
          npm install
          node bootstrapdb.js
          DEBUG=myapp:* npm start
      - name: ZAP Scan
        uses: zaproxy/action-full-scan@v0.4.0
        with:
          target: 'http://localhost:3000/'
