# .github/workflows/zap-scan.yml
name: ZAP-Test

on:
  push: 
    branches: [ main ]

jobs: 
  build: 
    runs-on: ubuntu-18.04
    steps: 
      - uses: actions/checkout@v2
      - name: docker compose
        run: docker-compose up --build --detach
      - name: docker pull
        run: docker pull ictu/zap2docker-weekly
      - name: running ZAP
        run: docker run --rm -v $(pwd):/zap/wrk/:rw -t ictu/zap2docker-weekly zap-baseline.py -I -j \
              -t https://https://enterprise.posindonesia.co.id \
              -r testreport.html \
              --hook=/zap/auth_hook.py \
              -z "auth.loginurl=https://https://enterprise.posindonesia.co.id/auth \
                  auth.username="994492078" \
                  auth.password="AAaa123*""
      
