name: ZAP-Test

on:
  push: 
    branches: [ main ]

jobs: 
  build: 
    runs-on: ubuntu-18.04
    steps: 
      - uses: actions/checkout@v2
      - name: Build Image
        run: docker build --tag stackhawk/nodeexpressvulny .
      - name: Run Docker Container
        run: docker run --rm --publish 3000:3000 --name nodeexpressvulny stackhawk/nodeexpressvulny
      - name: ZAP Scan
        uses: zaproxy/action-full-scan@v0.4.0
        with:
          target: 'http://localhost:3000/'
